### ISSUE TITLE
router.init does not work for commonJS

### ISSUE THREAD

**Issue by michaelgmcd** [BuckleTypes/bs-director#2]
From Discord:
----------------------------
hey @chenglou#3765, just wanted to let you know that for the webpack "electron-renderer" target (little different than the browser), I had to change the bs-director bindings to point to "director/build/director" instead of director in order to get router.init() to work (per this issue:
 https://github.com/flatiron/director/issues/332). Not sure if it's worth adding another external binding like "makeRouterForEnvOtherThanBrowser" (obv. a different name) or if it would be fine to just update the documentation. I copied the bindings over because it's ~4 lines of code, but here's the change:
```ocaml
external makeRouter : Js.t {..} => router =
  "Router" [@@bs.module "director/build/director"] [@@bs.new];
```
I can file an issue as well.

**Comment by mgmcdermott** [comment]
Referencing the issue as well:
https://github.com/flatiron/director/issues/332

**Comment by alcarvalho** [comment]
I had to do the same thing with webpack 2.6.1, too. In a regular web application.

**Comment by chenglou** [comment]
Done!
Tell me if you want a new release or something.

**Comment by guido4000** [comment]
I ran into the same problem. 
@chenglou it might be good to create  a new release.

**Comment by chenglou** [comment]
@guido4000 alright, done! Ping me if there's any problem
